# Dashboard backend configuration
datadir = "data"

# API server configuration
[server]
  host = "0.0.0.0"
  port = 3000

# Network monitoring configuration
[network]
  bundler_url                   = "https://bundler-staging.testnet-v2.alpenlabs.io/health"
  initial_status_wait_timeout_s = 30
  retry_policy_max_retries      = 5
  retry_policy_total_time_s     = 60
  rpc_url                       = "https://rpc-staging.testnet-v2.alpenlabs.io"
  sequencer_url                 = "https://rpc-staging.testnet-v2.alpenlabs.io"
  status_refetch_interval_s     = 10

# Bridge monitoring configuration
[bridge]
  esplora_request_timeout_s     = 5
  esplora_url                   = "https://esplora-staging.testnet-v2.alpenlabs.io"
  initial_status_wait_timeout_s = 5
  max_tx_confirmations          = 6
  status_refetch_interval_s     = 120
  withdrawal_pairing_batch_size = 1_000

  # Bridge operators configuration
  [[bridge.operators]]
    public_key = "025f9bfac3b160a0b9129d558ce29ab2df66ebbdd85dec1f5a2faf2e9de07acdfd"
    rpc_url    = "http://localhost:54231"

  [[bridge.operators]]
    public_key = "027098a1e38159f586536fabcb5537cdbb1454b1464c5c4a1bfd48de6c794d28c4"
    rpc_url    = "http://localhost:54232"

  [[bridge.operators]]
    public_key = "0288610184701307eef5dbb81ce1d974bc6940d21601a9656b565dab485321a03f"
    rpc_url    = "http://localhost:54233"

# Withdrawal-intent indexer configuration
[withdrawal_indexer]
  batch_size                   = 1_000
  eth_rpc_url                  = "https://alpen-staging.testnet-v2.alpenlabs.io"
  finality_lag                 = 12
  poll_interval_s              = 10
  start_block                  = 0
  withdrawal_denomination_sats = 100_000_000
