[toolchain]
  # update this after https://github.com/rust-lang/rust/issues/134044 is fixed.
  channel = "nightly-2025-06-01"
  components = [
    "cargo",
    "clippy",
    "rust-analyzer",
    "rust-docs",
    "rust-src",
    "rust-std",
    "rustc",
    "rustfmt",
    # "miri" # some of the secp256k1 FFIs fail with miri
  ]
